name: CI

on:
  workflow_dispatch:


jobs:
  ci:
    runs-on: windows-2022
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup premake
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Generate premake5 project
        run: premake5 vs2019
        shell: bash

      - name: Build 64bit release DLL
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 BigBaseV2.sln -m /warnaserror

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "bin/Release/BigBaseV2.dll")) {throw 1}

      - name: Rename DLL to YimMenu-dev-{GITHUB_SHA}.dll
        run: ren BigBaseV2.dll YimMenu-dev-${{github.sha}}.dll
        working-directory: bin/Release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: binary
          path: |
            bin/Release/YimMenu-dev-*.dll
