name: CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: windows-2022
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref }}
          submodules: recursive

      - name: Check CMake version
        run: cmake --version

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: amd64

      - name: Generate CMake project
        run: |
          cmake -D CMAKE_BUILD_TYPE=Release -D OPTIMIZE=True -D "CMAKE_POLICY_VERSION_MINIMUM=3.5" -S . -B build/x64-Release -G Ninja

      - name: Build 64bit Release DLL
        run: |
          cmake --build ./build/x64-Release --config Release --target YimMenu --

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "build/x64-Release/YimMenu.dll")) {throw 1}

      - name: Generate DLL hash
        run: |
          sha256sum YimMenu.dll > YimMenu.dll.sha256
        working-directory: build/x64-Release/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: |
            build/x64-Release/YimMenu.dll
            build/x64-Release/YimMenu.pdb
            build/x64-Release/YimMenu.map
            build/x64-Release/YimMenu.dll.sha256
          compression-level: 0
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dll
          path: |
            build/x64-Release/YimMenu.dll
          compression-level: 0